### ISSUE TITLE
Stuck on loading : Apis are failing hence project is not working

### ISSUE THREAD

**Issue by bikkimahato** [SaiPrasannaKrishna/react-foodDelivery#17]
Stuck on loading : Apis are failing hence project is not working
![image](https://user-images.githubusercontent.com/42492682/132524379-d525a8bd-ea36-4c6e-b2fe-5bdcab3abe91.png)

**Comment by Sunil4510** [comment]
hey i can do this

**Comment by SaiPrasannaKrishna** [comment]
I've updated the hosted URL - https://react-food-delivery.herokuapp.com/
Hope this resolves the issue :)
